# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbba077ffec24d2fe0f905c92454b5af"
name = "wehbook-test"
handle = "wehbook-test"
application_url = "https://switzerland-commodities-madonna-fujitsu.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "luke-media-dev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://switzerland-commodities-madonna-fujitsu.trycloudflare.com/auth/callback",
  "https://switzerland-commodities-madonna-fujitsu.trycloudflare.com/auth/shopify/callback",
  "https://switzerland-commodities-madonna-fujitsu.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
